[python]
version = “3.9.13”

[[python.packages]]
name = "antspyx"
version = "0.3.8"

[[python.packages]]
name = "aucmedi"
git = "https://github.com/frankkramer-lab/aucmedi.git"
rev = "c712cd4df63951ab93e28ff37f407bc2f3fcb4b7"

[[python.packages]]
name = "fpdf"
version = "1.7.2"

[[python.packages]]
name = "fslpy"
version = "3.13.2"

[[python.packages]]
name = "matplotlib"
version = "3.5.2"

[[python.packages]]
name = "numpy"
version = "1.24.3"

[[python.packages]]
name = "pandas"
version = "2.0.3"

[[python.packages]]
name = "tensorflow"
version = "2.11.1"

[[python.packages]]
name = "tk"
version = "0.1.0"

[[python.packages]]
name = "Pillow"
version = "10.0.0"
